config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls', namespace='events')), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.events_list, name='events_list'),
    path('<slug:category_slug>/', views.events_list, name='events_list_by_category' ),
    path('<int:id>/<slug:slug>/', views.event_detail, name='event_detail'),
]

events/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('events:events_list_by_category', args=[self.slug])


class Event(models.Model):
    category = models.ForeignKey(Category, related_name='events', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='events/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['title']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('events:event_detail', args=[self.id, self.slug])
    

events/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Event

def events_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    events = Event.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        events = events.filter(category=category)
    return render(request, 'events/event/list.html',
                            {'category': category,
                            'categories': categories,
                            'events': events})


def event_detail(request, id, slug):
    event = get_object_or_404(Event, id=id, slug=slug, available=True)
    return render(request, 'events/event/detail.html',
                            {'event': event})

events/templates/events/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Events App{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel='stylesheet'>
  </head>
  <body>
    <div id='header'>
      <a href="/" class="logo">Events App</a>
    </div>
    <div id="subheader">
      <div class="cart">
        Your cart is empty.
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

events/templates/events/event/detail.html
{% extends 'events/base.html' %}
{% load static %}
{% block title %}
  {{ event.title }}
{% endblock %}
{% block content %}
  <div class="event-detail">
    <img src="{% if event.image %}{{ event.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ event.title }}</h1>
    <h2>
      <a href="{{ event.category.get_absolute_url }}">
        {{ event.category }}
      </a>
    </h2>
    <p class="price">${{ event.price }}</p>
    {{ event.description|linebreaks }}
  </div>
{% endblock %}

events/templates/events/event/list.html
{% extends "events/base.html" %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}Events{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'events:events_list' %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %} class="selected" {% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}  
    </ul>
  </div>
  <div id="main" class="events-list">
    <h1>{% if category %}{{ category.name }}{% else %}Events{% endif %}</h1>
    {% for event in events %}
      <div class="item">
        <a href="{{ event.get_absolute_url}}">
          <img src="{% if event.image %}{{ event.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ event.get_absolute_url }}">{{ event.title }}</a>
        <br>
        ${{ event.price }}
      </div>
     {% endfor %} 
  </div>
{% endblock %}